In [1]:
import psycopg2
import pandas as pd

print('Manual connecting to the PostgreSQL database...\n\n\n')
conn = psycopg2.connect(
    host="postgres",
    database="dvdrental",
    user="postgres",
    password="example")

def create_pandas_table(sql_query, database = conn):
    table = pd.read_sql_query(sql_query, database)
    return table

# create a cursor
cur = conn.cursor()

tab_info = create_pandas_table("SELECT table_name FROM information_schema.tables WHERE table_type = 'BASE TABLE' AND table_schema NOT IN ('pg_catalog', 'information_schema');")

print('Tabulky v databazi:\n')
print(tab_info)

view_info = create_pandas_table("SELECT table_name FROM information_schema.tables WHERE table_type = 'VIEW' AND table_schema NOT IN ('pg_catalog', 'information_schema') AND table_name !~ '^pg_';")
print('\n\n\nViews v aktualni databazi: \n')
print(view_info)

#LIST USERS
list_users = create_pandas_table("SELECT usename FROM pg_user;")
print('\n\n\nUzivatele v aktualni databazi: \n')
print(list_users)

#RADKY v databazi
colum_info = create_pandas_table("SELECT column_name FROM information_schema.columns WHERE table_name = 'store';")

print('\n\n\nINFO O tabulce: *JMENOTABULKY* \n')
print(colum_info)

#Detailni info o radcich
detail_info = create_pandas_table("SELECT ordinal_position, column_name, data_type, column_default, is_nullable, character_maximum_length, numeric_precision FROM information_schema.columns WHERE table_name = 'store' ORDER BY ordinal_position;")

print('\n\n Detailní info o tabulce : *JMENOTABULKY* \n')
print(detail_info)

#LIST TRIGGERS#
trigger_info = create_pandas_table("SELECT DISTINCT trigger_name FROM information_schema.triggers WHERE trigger_schema NOT IN ('pg_catalog', 'information_schema');")

print('\n\n List of triggrs : \n')
print(trigger_info)

#Detailni LIST TRIGGERS (pro vsechno v databazi)#
#Detail_trigger_info = create_pandas_table("SELECT * FROM information_schema.triggers WHERE trigger_schema NOT IN ('pg_catalog', 'information_schema');")
#print('\n\n Detailni List of triggrs : \n')
#print(Detail_trigger_info)

# close the communication with the PostgreSQL
cur.close()
conn.close()

Manual connecting to the PostgreSQL database...



Tabulky v databazi:

       table_name
0           actor
1           store
2         address
3        category
4            city
5         country
6        customer
7      film_actor
8   film_category
9       inventory
10       language
11         rental
12          staff
13        payment
14           film



Views v aktualni databazi:

                   table_name
0                  actor_info
1               customer_list
2                   film_list
3  nicer_but_slower_film_list
4      sales_by_film_category
5              sales_by_store
6                  staff_list



Uzivatele v aktualni databazi:

    usename
0  postgres



INFO O tabulce: *JMENOTABULKY*

        column_name
0          store_id
1  manager_staff_id
2        address_id
3       last_update


 Detailní info o tabulce : *JMENOTABULKY*

   ordinal_position       column_name                    data_type  \
0                 1          store_id                      integer
1                 2  manager_staff_id                     smallint
2                 3        address_id                     smallint
3                 4       last_update  timestamp without time zone

                            column_default is_nullable  \
0  nextval('store_store_id_seq'::regclass)          NO
1                                     None          NO
2                                     None          NO
3                                    now()          NO

  character_maximum_length  numeric_precision
0                     None               32.0
1                     None               16.0
2                     None               16.0
3                     None                NaN


 List of triggrs :

            trigger_name
0  film_fulltext_trigger
1           last_updated

NameError: name 'cur' is not defined